<?php

namespace ED\AlbumBundle\Repository;
use Doctrine\ORM\EntityRepository;
use ED\AlbumBundle\Entity\Image;
use ED\UserBundle\EDUserBundle;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
	
	public function getLastAlbums(int $limit, int $userId)
	{
		$qb = $this
			->createQueryBuilder('a')
			->where('a.owner = :owner')
			->setParameter('owner', $userId)
			->setMaxResults($limit)
			->orderBy('a.created','DESC')
		;
		return $qb
			->getQuery()
			->getResult()
		;
	}
	
	
	public function getAlbumsFromOneImage(Image $image, int $userId)
	{
		$qb = $this
		->createQueryBuilder('a')
		->join('a.images', 'i')
		->where('a.owner = :owner')
		->setParameter('owner', $userId)
		->andWhere('i.id = :image_id')
		->setParameter('image_id', $image->getId())
		->orderBy('a.created','ASC')
		;
		return $qb
		->getQuery()
		->getResult()
		;
	}
}
